site_name: Johan Hallberg Szabadv√°ry
site_url: https://johan-hallberg-szabadvary.github.io/
repo_url: https://github.com/johan-hallberg-szabadvary/johan-hallberg-szabadvary.github.io
repo_name: GitHub

theme:
  name: material
  palette:
    - scheme: default
      primary: slate
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: slate
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - header.autohide

plugins:
  - search
  - social
  - blog:
      post_url_date_format: yyyy/MM/dd

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/egonmedhatten  # Your coding account
    - icon: fontawesome/solid/envelope
      link: mailto:johan.hallberg.szabadvary@ju.se # (Update if needed)

nav:
  - Home: index.md
  - News: blog/
  - Research: research.md
  - CV: cv.md

markdown_extensions:
# This allows the { align=left } styling on images
- attr_list

# This enables the :material-icon: codes
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg